### ISSUE TITLE
Set locale for faker

### ISSUE THREAD

**Issue by k2rn** [vierge-noire/cakephp-fixture-factories#71] opened 2021-04-23 07:03 UTC
Is there any way to set locale for faker?

I saw `Factory/BaseFactory.php`, it seems don't care about locale.

```php
    /**
     * @return \Faker\Generator
     */
    public function getFaker(): Generator
    {
        if (is_null(self::$faker)) {
            $faker = Factory::create();
            $faker->seed(1234);
            self::$faker = $faker;
        }

        return self::$faker;
    }
```

To use other locale, I should extend this method to create localized faker so far?

**Comment by k2rn** [comment] 2021-04-23 07:20
It cannot extend this method.
self::$faker is private.
It has no way to change this locale so far.

**Comment by k2rn** [comment] 2021-04-23 07:43
In sub class, redefine `private static $faker` makes it work like this.

```
    /**
     * @var Generator
     */
    private static $faker;

    /**
     * @var string
     */
    protected $locale = 'ja_JP';

    /**
     * @return \Faker\Generator
     */
    public function getFaker(): Generator
    {
        if (is_null(self::$faker)) {
            $faker = Factory::create($this->locale);
            $faker->seed(1234);
            self::$faker = $faker;
        }

        return self::$faker;
    }

```

But it would be preferable to prepare way to change locale settings.

**Comment by pabloelcolombiano** [comment] 2021-04-23 07:51
Hi @k2rn ,

yes we can work this out., $faker should definitely be protected.

In addition, we could have protected $locale variable, just as you did, in order to set the locale of a given factory.

But eventually, what you probably want is that faker uses the locale defined in I18n, right?

**Comment by k2rn** [comment] 2021-04-23 08:16
Hi @pabloelcolombiano 

Thanks for reply, yeah it would be nice that `I18N::getLocale()` can be set in testing.
But it may have case using specified locale, so it would be better let it configurable.

**Comment by pabloelcolombiano** [comment] 2021-04-23 22:30
Hi @k2rn 

Putting my hands into the code, I found out that there is a good reason to have $faker private. This is instantiated once for all factories, and therefore it is not wished to have it modifiable if afterwards. The work around you propose is dangerous, because your factories do not necessarily work on the same seed. This will create collisions in your unique fields.

I have implemented the fact that Faker takes your apps I18n locale per default, if it supports it.

You may have a look at the commits above. Or try it on the `next` branch or `cake3_next` branch. Let me know if this works for you, and I'll put it in this coming release.

**Comment by k2rn** [comment] 2021-04-23 22:49
@pabloelcolombiano 

Are there any reasons for it should be static?
It's better `protected $faker` than `private static $faker` .
And it's possible, `function setFaker(Generator $faker)` is more suitable for each test cases that need any other faker features.

faker has extended functions in some locale. https://github.com/fzaninotto/Faker#language-specific-formatters
And it throws exception when the extended function was called.
That is why I need set locale and my opition for it should not static.

**Comment by pabloelcolombiano** [comment] 2021-04-24 19:26
The $faker should be static, and private, because it is set once and for all fixtures. You do not want ArticleFactory to work with a faker, and the same ArticleFactory working with a different instance of fakers, because they might collide, say for example if both have the same `title`, with `title` being unique.

But you are right in the sense that the developer should be free to modify faker at its will between tests if required. It meets in many ways the issues #4 and #5 which we have not solved so far.

I think that the problem is that $faker is a property in the BaseFactory, whilst it should be defined in a different class, independent of the factories. The factories would pick up the faker defined by the user from there.

We could also think of having a Faker registry, where each factory class could potentially have its own version of Faker. You would have for example the SettingFactory delivering options in English, and the UserFactory delivering names in Japanese.

@k2rn is this going in the direction you meant? Is it clear for you why $faker should be static and private?

@pakacuda what do you think of having `$faker` handled from a different dedicated class?

**Comment by k2rn** [comment] 2021-04-25 01:09
@pabloelcolombiano I see your reasons for this.

> We could also think of having a Faker registry, where each factory class could potentially have its own version of Faker. You would have for example the SettingFactory delivering options in English, and the UserFactory delivering names in Japanese.

That's right.

I expected clear databases in each test cases, cake didn't do so far. So this way is fit for your community, I might avoid it by own.
I will create own base factory class that extends your base factory like this.

```php
    /**
     * @var Generator
     */
    protected $_faker;

    /**
     * @var string
     */
    protected $locale = 'ja_JP';

    /**
     * @return \Faker\Generator
     */
    public function getFaker(): Generator
    {
        if ($this->_faker === null) {
            $faker = Factory::create($this->locale);
            $faker->seed(1234);
            $this->_faker = $faker;
        }

        return $this->_faker;
    }

    public function setFaker(Generator $faker): void
    {
        $this->_faker = $faker;
    }
```

This must not be harm your community.

**Comment by pabloelcolombiano** [comment] 2021-04-25 02:47
@k2rn the implementation you propose is covered by the modification I made on the `next` branch.
See this [line](https://github.com/vierge-noire/cakephp-fixture-factories/commit/f4419a09ebb72c4f115719dd4ece6f03d14e1ceb#diff-4141edddd3255a92d3151cfee2b7e44cf03a474ccd9a51f0b279e16eddda3cc6R214).
If your application has its locale defined to Japanese, the plugin will pick up `ja_JP` for your factories.

If you could take a minute to test that and confirm, I can ship that in a new release.

**Comment by k2rn** [comment] 2021-04-25 02:54
@pabloelcolombiano OK, I think it's no problem in project that have just one locale.

**Comment by pabloelcolombiano** [comment] 2021-04-25 02:55
Alright, just give me a short go once you have tested the implementation on `next` (or `cake3_next` if you are on CakePHP 3), and I'll ship that.

**Comment by k2rn** [comment] 2021-04-25 03:04
I'm using 4, appreciate if branche `next` could be shipped.

**Comment by pabloelcolombiano** [comment] 2021-04-25 03:12
This is now featured on [v2.2.2](https://github.com/vierge-noire/cakephp-fixture-factories/releases/tag/v2.2.2).

I will close this discussion for now. Thanks for the contribution @k2rn !

**Closed by pabloelcolombiano** 2021-04-25 03:12 UTC
Labels: enhancement
